import json
import os
import glob
from collections import defaultdict

class AIRetrospectiveAnalyzer:
    """
    Parses all daily JSON logs generated by the backtester, 
    calculates highly specific quantitative metrics (win rate by regime, etc),
    and generates a detailed Markdown log for the AI/Human.
    """

    def __init__(self, journal_dir=r"c:\Users\Harish\docs\OneDrive\Desktop\jackv2\jack\journal"):
        self.journal_dir = journal_dir
        self.logs_dir = os.path.join(self.journal_dir, "logs")
        self.output_path = os.path.join(self.journal_dir, "ai_retrospective_log.md")

    def run_analysis(self):
        log_files = glob.glob(os.path.join(self.logs_dir, "????-??-??.json"))
        
        if not log_files:
            print("No daily logs found.")
            return

        print(f"Found {len(log_files)} daily logs. Processing...")

        # Quantitative tracking bins
        strat_regime_stats = defaultdict(lambda: {"wins": 0, "losses": 0, "total_pnl": 0.0})
        strat_gap_stats = defaultdict(lambda: {"wins": 0, "losses": 0, "total_pnl": 0.0})
        total_pnl_all = 0.0
        total_trades = 0

        for log_file in log_files:
            try:
                with open(log_file, 'r', encoding='utf-8') as f:
                    data = json.load(f)
            except Exception as e:
                print(f"Error reading {log_file}: {e}")
                continue

            day_pnl = 0
            
            # Extract morning scan context
            scan = data.get("morning_scan", {})
            regime = scan.get("regime", "unknown")
            gap_type = scan.get("gap_type", "unknown")
            
            trades = data.get("trades", [])
            for t in trades:
                strat = t.get("strategy", "unknown")
                pnl = t.get("net_pnl", 0)
                is_win = pnl > 0
                
                total_trades += 1
                total_pnl_all += pnl
                day_pnl += pnl
                
                # Regime Analysis
                r_stats = strat_regime_stats[f"{strat} | {regime}"]
                if is_win: r_stats["wins"] += 1
                else: r_stats["losses"] += 1
                r_stats["total_pnl"] += pnl
                
                # Gap Type Analysis
                g_stats = strat_gap_stats[f"{strat} | {gap_type}"]
                if is_win: g_stats["wins"] += 1
                else: g_stats["losses"] += 1
                g_stats["total_pnl"] += pnl

        # Generate the Markdown Report
        md_lines = []
        md_lines.append("# AI Retrospective Analysis Log")
        md_lines.append("> Auto-generated reflection quantifying strategy performance across market contexts.\n")
        
        md_lines.append("## 1. High-Level Overview")
        md_lines.append(f"- **Total Trades Analyzed**: {total_trades}")
        md_lines.append(f"- **Total Net P&L**: Rs{total_pnl_all:,.2f}")
        md_lines.append("")

        md_lines.append("## 2. Strategy Performance by Market Regime")
        md_lines.append("| Strategy & Regime | Win/Loss | Win% | Total P&L |")
        md_lines.append("|-------------------|----------|------|-----------|")
        
        for key, stats in sorted(strat_regime_stats.items()):
            w, l = stats["wins"], stats["losses"]
            total = w + l
            win_pct = (w / total) * 100 if total > 0 else 0
            pnl = stats["total_pnl"]
            pnl_color = "🟢" if pnl >= 0 else "🔴"
            md_lines.append(f"| {key} | {w}W / {l}L | {win_pct:.1f}% | {pnl_color} Rs{pnl:,.0f} |")
        md_lines.append("")

        md_lines.append("## 3. Strategy Performance by Morning Gap Type")
        md_lines.append("| Strategy & Gap | Win/Loss | Win% | Total P&L |")
        md_lines.append("|-------------------|----------|------|-----------|")
        
        for key, stats in sorted(strat_gap_stats.items()):
            w, l = stats["wins"], stats["losses"]
            total = w + l
            win_pct = (w / total) * 100 if total > 0 else 0
            pnl = stats["total_pnl"]
            pnl_color = "🟢" if pnl >= 0 else "🔴"
            md_lines.append(f"| {key} | {w}W / {l}L | {win_pct:.1f}% | {pnl_color} Rs{pnl:,.0f} |")
        md_lines.append("")

        md_lines.append("## 4. Pending AI Decisions & Action Loop")
        md_lines.append("*(The AI agent will read this log to formulate structural changes to the codebase and record its decisions below in the next phase).*")
        
        md_content = "\n".join(md_lines)
        
        with open(self.output_path, 'w', encoding='utf-8') as f:
            f.write(md_content)
        
        print(f"Generated AI Retrospective Log at: {self.output_path}")


if __name__ == "__main__":
    analyzer = AIRetrospectiveAnalyzer()
    analyzer.run_analysis()
