"""
HTML Report Generator.

Generates a self-contained HTML report with Chart.js charts,
equity curves, performance tables, and Monte Carlo results.
"""

import json
import os


class ReportGenerator:
    """Generate a self-contained HTML backtest report."""

    def __init__(self, results: dict, benchmarks: dict = None,
                 monte_carlo: dict = None, walk_forward: dict = None,
                 journal_path: str = "journal/logs/"):
        self.results = results
        self.benchmarks = benchmarks or {}
        self.monte_carlo = monte_carlo or {}
        self.walk_forward = walk_forward or {}
        self.journal_path = journal_path

    def generate(self, output_path: str = "report.html") -> None:
        """Generate a single self-contained HTML file."""
        equity_data = json.dumps(
            self.results.get("equity_curve", []),
            default=str,
        )

        trade_log = self.results.get("trade_log", [])
        top_wins = sorted(trade_log, key=lambda t: t.get("net_pnl", 0), reverse=True)[:10]
        top_losses = sorted(trade_log, key=lambda t: t.get("net_pnl", 0))[:10]

        by_strategy = self.results.get("by_strategy", {})
        by_day = self.results.get("by_day", {})
        by_month = self.results.get("by_month", {})

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Jack — Backtest Report</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<style>
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{
    font-family: 'Segoe UI', system-ui, sans-serif;
    background: #0d1117; color: #c9d1d9;
    padding: 2rem; line-height: 1.6;
}}
.container {{ max-width: 1200px; margin: 0 auto; }}
h1 {{ color: #58a6ff; font-size: 2rem; margin-bottom: 0.5rem; }}
h2 {{
    color: #58a6ff; font-size: 1.3rem; margin-top: 2rem;
    border-bottom: 1px solid #21262d; padding-bottom: 0.5rem;
}}
.summary-grid {{
    display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 1rem; margin: 1.5rem 0;
}}
.metric-card {{
    background: #161b22; border: 1px solid #21262d; border-radius: 8px;
    padding: 1rem; text-align: center;
}}
.metric-value {{
    font-size: 1.8rem; font-weight: bold; font-family: 'Courier New', monospace;
}}
.metric-label {{ font-size: 0.85rem; color: #8b949e; }}
.positive {{ color: #3fb950; }}
.negative {{ color: #f85149; }}
table {{
    width: 100%; border-collapse: collapse; margin: 1rem 0;
    background: #161b22; border-radius: 8px; overflow: hidden;
}}
th {{
    background: #21262d; color: #58a6ff; padding: 0.75rem;
    text-align: left; font-size: 0.85rem;
}}
td {{
    padding: 0.75rem; border-bottom: 1px solid #21262d;
    font-family: 'Courier New', monospace; font-size: 0.9rem;
}}
tr:hover {{ background: #1c2128; }}
.chart-container {{
    background: #161b22; border: 1px solid #21262d;
    border-radius: 8px; padding: 1rem; margin: 1rem 0;
}}
canvas {{ max-height: 400px; }}
.footer {{ margin-top: 3rem; color: #484f58; text-align: center; font-size: 0.8rem; }}
</style>
</head>
<body>
<div class="container">
<h1>🎯 Jack — Backtest Report</h1>
<p style="color: #8b949e;">
Period: {self.results.get('start_date', 'N/A')} -> {self.results.get('end_date', 'N/A')} |
Trading days: {self.results.get('total_days', 0)} |
Generated by Jack Backtesting Engine
</p>

<h2>📊 Summary</h2>
<div class="summary-grid">
{self._metric_card("Total Trades", self.results.get('total_trades', 0))}
{self._metric_card("Win Rate", f"{self.results.get('win_rate', 0):.1f}%",
    "positive" if self.results.get('win_rate', 0) > 50 else "negative")}
{self._metric_card("Net P&L", f"Rs{self.results.get('net_pnl', 0):,.0f}",
    "positive" if self.results.get('net_pnl', 0) > 0 else "negative")}
{self._metric_card("Return", f"{self.results.get('return_pct', 0):.2f}%",
    "positive" if self.results.get('return_pct', 0) > 0 else "negative")}
{self._metric_card("Sharpe", f"{self.results.get('sharpe_ratio', 0):.3f}",
    "positive" if self.results.get('sharpe_ratio', 0) > 1 else "")}
{self._metric_card("Max Drawdown", f"{self.results.get('max_drawdown_pct', 0):.2f}%", "negative")}
{self._metric_card("Profit Factor", f"{self.results.get('profit_factor', 0):.3f}",
    "positive" if self.results.get('profit_factor', 0) > 1 else "negative")}
{self._metric_card("Avg P&L", f"Rs{self.results.get('avg_pnl', 0):,.0f}",
    "positive" if self.results.get('avg_pnl', 0) > 0 else "negative")}
</div>

<h2>📈 Equity Curve</h2>
<div class="chart-container">
<canvas id="equityChart"></canvas>
</div>

<h2>🎯 Strategy Breakdown</h2>
{self._strategy_table(by_strategy)}

<h2>📅 Day of Week</h2>
{self._day_table(by_day)}

<h2>🏆 Top 10 Best Trades</h2>
{self._trade_table(top_wins)}

<h2>💀 Top 10 Worst Trades</h2>
{self._trade_table(top_losses)}

{self._monte_carlo_section()}

<div class="footer">
<p>Jack — Deterministic Bank Nifty Backtesting Engine | Built with Claude Code</p>
</div>
</div>

<script>
const equityData = {equity_data};
const labels = equityData.map((d, i) => d[0] || i);
const values = equityData.map(d => d[1]);
new Chart(document.getElementById('equityChart'), {{
    type: 'line',
    data: {{
        labels: labels,
        datasets: [{{
            label: 'Equity (Rs)',
            data: values,
            borderColor: '#58a6ff',
            backgroundColor: 'rgba(88, 166, 255, 0.1)',
            fill: true,
            tension: 0.1,
            pointRadius: 0,
        }}]
    }},
    options: {{
        responsive: true,
        plugins: {{ legend: {{ labels: {{ color: '#c9d1d9' }} }} }},
        scales: {{
            x: {{ ticks: {{ color: '#8b949e', maxTicksLimit: 20 }} }},
            y: {{
                ticks: {{
                    color: '#8b949e',
                    callback: v => 'Rs' + v.toLocaleString()
                }}
            }}
        }}
    }}
}});
</script>
</body>
</html>"""

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html)
        print(f"Report generated: {output_path}")

    def _metric_card(self, label: str, value, css_class: str = "") -> str:
        return (
            f'<div class="metric-card">'
            f'<div class="metric-value {css_class}">{value}</div>'
            f'<div class="metric-label">{label}</div></div>'
        )

    def _strategy_table(self, by_strategy: dict) -> str:
        if not by_strategy:
            return "<p>No strategy data available.</p>"
        rows = ""
        for name, data in by_strategy.items():
            pnl = data.get("pnl", data.get("net_pnl", 0))
            css = "positive" if pnl > 0 else "negative"
            rows += (
                f"<tr><td>{name}</td><td>{data.get('trades', 0)}</td>"
                f"<td>{data.get('win_rate', data.get('win_rate_pct', 0))}%</td>"
                f"<td class='{css}'>Rs{pnl:,.0f}</td>"
                f"<td>{data.get('profit_factor', 'N/A')}</td></tr>"
            )
        return (
            f"<table><tr><th>Strategy</th><th>Trades</th><th>Win Rate</th>"
            f"<th>Net P&L</th><th>Profit Factor</th></tr>{rows}</table>"
        )

    def _day_table(self, by_day: dict) -> str:
        if not by_day:
            return "<p>No day-of-week data available.</p>"
        rows = ""
        for day in ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]:
            if day in by_day:
                d = by_day[day]
                pnl = d.get("net_pnl", 0)
                css = "positive" if pnl > 0 else "negative"
                rows += (
                    f"<tr><td>{day}</td><td>{d.get('trade_count', 0)}</td>"
                    f"<td>{d.get('win_rate', 0)}%</td>"
                    f"<td class='{css}'>Rs{pnl:,.0f}</td></tr>"
                )
        return (
            f"<table><tr><th>Day</th><th>Trades</th><th>Win Rate</th>"
            f"<th>Net P&L</th></tr>{rows}</table>"
        )

    def _trade_table(self, trades: list) -> str:
        if not trades:
            return "<p>No trades.</p>"
        rows = ""
        for t in trades:
            pnl = t.get("net_pnl", 0)
            css = "positive" if pnl > 0 else "negative"
            rows += (
                f"<tr><td>{t.get('entry_date', '')}</td>"
                f"<td>{t.get('strategy', '')}</td>"
                f"<td>{t.get('direction', '')}</td>"
                f"<td>{t.get('entry_price', 0):.1f}</td>"
                f"<td>{t.get('exit_price', 0):.1f}</td>"
                f"<td class='{css}'>Rs{pnl:,.0f}</td>"
                f"<td>{t.get('exit_reason', '')}</td></tr>"
            )
        return (
            f"<table><tr><th>Date</th><th>Strategy</th><th>Dir</th>"
            f"<th>Entry</th><th>Exit</th><th>P&L</th><th>Reason</th>"
            f"</tr>{rows}</table>"
        )

    def _monte_carlo_section(self) -> str:
        if not self.monte_carlo:
            return ""
        mc = self.monte_carlo
        return f"""
<h2>🎲 Monte Carlo Validation</h2>
<div class="summary-grid">
{self._metric_card("Percentile Rank", f"{mc.get('percentile_rank', 0):.1f}%",
    "positive" if mc.get('percentile_rank', 0) > 75 else "negative")}
{self._metric_card("p-value", f"{mc.get('p_value', 1):.4f}",
    "positive" if mc.get('p_value', 1) < 0.05 else "negative")}
{self._metric_card("Actual Equity", f"Rs{mc.get('actual_final_equity', 0):,.0f}")}
{self._metric_card("Mean Shuffled", f"Rs{mc.get('mean_shuffled_equity', 0):,.0f}")}
</div>
<p style="margin: 1rem 0; padding: 1rem; background: #161b22; border-radius: 8px;">
{mc.get('interpretation', 'No interpretation available.')}
</p>
"""
